development: &defaults
  # Options for the directory structure of your project
  directoryStructure:

    # The folder location of the compiled scripts and assets
    distributionRoot: ./dist 
    
    # The source folder for scripts and assets    
    sourceRoot: ./src 

    # The relative location of all JavaScript / CoffeeScript source files
    #   e.g. If your files live at './src/scripts', this option should be 'scripts'
    scriptsFolder: js 

    # The relative location of all style source files
    #   e.g. If your files live at './src/scripts', this option should be 'scripts'
    stylesFolder: css

    # The relative location of all image source files
    #   e.g. If your files live at './src/image', this option should be 'scripts'
    imagesFolder: images

  # Options for handling compiliation of javascript
  scriptOptions:

    # Browserify options
    browserify:

      # The relative location of the main 'entry point' of your app
      #  - This specifies where browserify will start to read its dependency graph
      #    and include files in your finalized javascript file
      #
      #  e.g. If the entry point in your app is './src/js/main.js', this option 
      #       should be main.js
      entryFile: app.js

      # A list of transforms to pass to browserify
      #  - The babelify transform is required and configured for you (see below)
      #  - Gulp will attempt to install any missing transform modules, but should not be
      #    relied upon
      #  - Others must be included in your npm package (otherwise build will fail)
      #  - See https://github.com/substack/node-browserify/wiki/list-of-transforms
      #    for a list of available transforms
      transform:
        - babelify

    # Babelify options
    babelify:

      # A list of babelify presets to use. See http://babeljs.io/docs/plugins/ for more details
      # Gulp will attempt to install any missing presets, but should not be relied upon
      presets:
        - es2015
        - react

    # Include sourcemaps
    sourcemaps: true

    plugins:
      - gulp-uglify


test:
  <<: *defaults
  


production:
  <<: *defaults